### PR TITLE
add removeSome method to remove by string contains in key

### PR DESCRIPTION
**Pull request by SkeLLLa**
I've added method to be able to remove cache items by a key's substring. This method is not so fast as direct removal by key, because it iterates over whole hash map, but it provides functionality that couldn't be achieved before.

This is quiet rough implementation mostly because I'm not c++ developer and maybe it's 3rd time in my life when I used to code in c++ :). So I will be grateful if you review this code.

May be it will be better to add something like removing by wildcard, but as my c++ knowledge is very limited, I not tried to do it, but I think it shouldn't be hard enough.

### CODE REVIEW

**Comment by SkeLLLa** [comment]
Also may be it's better to make method like getSome that will return substring matches by key, and to achieve `removeSome` functionality just use something like:
```js
lru.getSome('subkey').forEach((item) => {lru.remove(item.key})
```

**Comment by denghongcai** [comment]
thanks for your pr ! Maybe it's better to add a method to iterate over the cache and do the `remove` and `get` operation using javascript ?

**Comment by SkeLLLa** [comment]
@denghongcai maybe it will be good to have 'keys' method like in `lru-native` module. But I thought that c++ function can perform better than iterating in js, so if you need performance you can call it, and if you need some sophisticated comparisons, then you can use `keys` + `get` or `remove`.

Also I've tried to use `std::find_if` in native code, but without success. I think with it code will look better.

**Comment by denghongcai** [comment]
in my opinion, batch operation is a kind of low frequency operation, which means add a `keys` method is enough and agile. after all, lru is a cache not a NoSQL database...

**Comment by SkeLLLa** [comment]
@denghongcai I agree with you about adding `keys` method. It will make this lru module much more flexible. 

As for more specific methods, I think that they can be also useful in some cases and allow process them inside C++ code, especially some kind of operations that need reduced amount of keys (when you want to perform an operation on a subset of items). E.g. if you have cache with ~50k keys and you need remove just some of them, returning whole subset of keys to node can consume a big amount of memory depending on key length. And also you'll need at least 1 additional local variable in js to perform `filter` or something like this operation.

So it would be great if method `keys` can be called in two ways:
* without arguments - returns all keys in lru (or maybe just not expired keys)
* with argument - return keys that contain this argument (so if you pass 'bc' as aan argument, keys should return keys like 'abc', 'bcd, but not 'dce').

**Comment by SkeLLLa** [comment]
@denghongcai Rewrited prevoius code to `keys` method, as described above. Feel free to modify it if you don't want functionality with filtering by subkey or if you know how some will work better :).

Thanks.

**Comment by denghongcai** [comment]
+ lru-addon@1.1.0

**Comment by SkeLLLa** [comment]
@denghongcai great, thanks!

**Pull request merged**
